### ISSUE TITLE
Suggest using environment.yml instead of requirements.txt

### ISSUE THREAD

**Issue by DWFlanagan** [WileyIntelligentSolutions/cookielite#18]
In the `readme.md` template for new projects, I think suggesting to use `environment.yml` would be more robust than `requirements.txt` since it should work across operating systems and includes packages installed with `pip` as well.

From the [conda blog](https://www.anaconda.com/moving-conda-environments/):

> Sharing a project environment across platforms and operating systems can also be done using the – -export option to generate an environment.yml file. The difference between a spec list and an environment.yml file is that the environment.yml file is not operating system specific and is formatted using YAML. Only the package names are listed and conda is left to build the environment based on the package names. Another difference is that – -export also includes packages installed using pip whereas a spec list does not.

**Comment by adamstimb** [comment]
Done!
